# Site settings
title: Carmen´s Personal Website
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Carmen would like to say hi on her new website!!! Gracias para ver.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
